-- MySQL Script generated by MySQL Workbench
-- Sun Jul 11 15:21:53 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `Endereco`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Endereco` ;

CREATE TABLE IF NOT EXISTS `Endereco` (
  `cep` INT NOT NULL,
  `cidade` VARCHAR(45) NULL,
  PRIMARY KEY (`cep`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Funcionarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Funcionarios` ;

CREATE TABLE IF NOT EXISTS `Funcionarios` (
  `idFuncionarios` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `data_nascimento` DATE NOT NULL,
  `cpf` INT NOT NULL,
  `genero` VARCHAR(45) NULL,
  `email` VARCHAR(45) NOT NULL,
  `cargo` VARCHAR(45) NOT NULL,
  `Logradouro` VARCHAR(100) NOT NULL,
  `Endereco_cep` INT NOT NULL,
  `Gerente_Farma_Funcionarios_idFuncionarios` INT NOT NULL,
  PRIMARY KEY (`idFuncionarios`),
  CONSTRAINT `fk_Funcionarios_Gerente_Farma1`
    FOREIGN KEY (`Gerente_Farma_Funcionarios_idFuncionarios`)
    REFERENCES `Gerente_Farma` (`Funcionarios_idFuncionarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Funcionarios_Endereco1`
    FOREIGN KEY (`Endereco_cep`)
    REFERENCES `Endereco` (`cep`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Funcionarios_Gerente_Farma1_idx` ON `Funcionarios` (`Gerente_Farma_Funcionarios_idFuncionarios` ASC) VISIBLE;

CREATE INDEX `fk_Funcionarios_Endereco1_idx` ON `Funcionarios` (`Endereco_cep` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Gerente_Farma`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Gerente_Farma` ;

CREATE TABLE IF NOT EXISTS `Gerente_Farma` (
  `Funcionarios_idFuncionarios` INT NOT NULL,
  `crf` INT NOT NULL,
  PRIMARY KEY (`Funcionarios_idFuncionarios`),
  CONSTRAINT `fk_Gerente_Farma_Funcionarios1`
    FOREIGN KEY (`Funcionarios_idFuncionarios`)
    REFERENCES `Funcionarios` (`idFuncionarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Fornecedor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Fornecedor` ;

CREATE TABLE IF NOT EXISTS `Fornecedor` (
  `idFornecedor` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `cnpj` INT NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `Logradouro` VARCHAR(100) NOT NULL,
  `Endereco_Forn_cep` INT NOT NULL,
  `Gerente_Farma_Funcionarios_idFuncionarios` INT NOT NULL,
  PRIMARY KEY (`idFornecedor`),
  CONSTRAINT `fk_Fornecedor_Gerente_Farma1`
    FOREIGN KEY (`Gerente_Farma_Funcionarios_idFuncionarios`)
    REFERENCES `Gerente_Farma` (`Funcionarios_idFuncionarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Fornecedor_Endereco_Forn1`
    FOREIGN KEY (`Endereco_Forn_cep`)
    REFERENCES `Endereco` (`cep`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Fornecedor_Gerente_Farma1_idx` ON `Fornecedor` (`Gerente_Farma_Funcionarios_idFuncionarios` ASC) VISIBLE;

CREATE INDEX `fk_Fornecedor_Endereco_Forn1_idx` ON `Fornecedor` (`Endereco_Forn_cep` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Compras`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Compras` ;

CREATE TABLE IF NOT EXISTS `Compras` (
  `idCompras` INT NOT NULL,
  `no_nota_fiscal` INT NOT NULL,
  `data_compra` DATE NOT NULL,
  `valor_total` DECIMAL NOT NULL,
  `Fornecedor_idFornecedor` INT NOT NULL,
  `Gerente_Farma_Funcionarios_idFuncionarios` INT NOT NULL,
  PRIMARY KEY (`idCompras`),
  CONSTRAINT `fk_Compras_Fornecedor`
    FOREIGN KEY (`Fornecedor_idFornecedor`)
    REFERENCES `Fornecedor` (`idFornecedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Compras_Gerente_Farma1`
    FOREIGN KEY (`Gerente_Farma_Funcionarios_idFuncionarios`)
    REFERENCES `Gerente_Farma` (`Funcionarios_idFuncionarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Compras_Fornecedor_idx` ON `Compras` (`Fornecedor_idFornecedor` ASC) VISIBLE;

CREATE INDEX `fk_Compras_Gerente_Farma1_idx` ON `Compras` (`Gerente_Farma_Funcionarios_idFuncionarios` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Medicamentos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Medicamentos` ;

CREATE TABLE IF NOT EXISTS `Medicamentos` (
  `idMedicamentos` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `lab_marca` VARCHAR(45) NOT NULL,
  `principio_ativo` VARCHAR(45) NOT NULL,
  `categoria` VARCHAR(45) NOT NULL,
  `quantidade` INT NOT NULL,
  `unidade` VARCHAR(45) NOT NULL,
  `lote` INT NOT NULL,
  `total_estoque` INT NOT NULL,
  PRIMARY KEY (`idMedicamentos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Items`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Items` ;

CREATE TABLE IF NOT EXISTS `Items` (
  `Compras_idCompras` INT NOT NULL,
  `seq_item` INT NOT NULL,
  `Medicamentos_idMedicamentos` INT NOT NULL,
  `quantidade` INT NOT NULL,
  `preco_unitario` DECIMAL NOT NULL,
  PRIMARY KEY (`Compras_idCompras`, `seq_item`),
  CONSTRAINT `fk_Items_Compras1`
    FOREIGN KEY (`Compras_idCompras`)
    REFERENCES `Compras` (`idCompras`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Items_Medicamentos1`
    FOREIGN KEY (`Medicamentos_idMedicamentos`)
    REFERENCES `Medicamentos` (`idMedicamentos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Items_Compras1_idx` ON `Items` (`Compras_idCompras` ASC) VISIBLE;

CREATE INDEX `fk_Items_Medicamentos1_idx` ON `Items` (`Medicamentos_idMedicamentos` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Medico`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Medico` ;

CREATE TABLE IF NOT EXISTS `Medico` (
  `Funcionarios_idFuncionarios` INT NOT NULL,
  `crm` INT NOT NULL,
  PRIMARY KEY (`Funcionarios_idFuncionarios`),
  CONSTRAINT `fk_Medico_Funcionarios1`
    FOREIGN KEY (`Funcionarios_idFuncionarios`)
    REFERENCES `Funcionarios` (`idFuncionarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Paciente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Paciente` ;

CREATE TABLE IF NOT EXISTS `Paciente` (
  `idPaciente` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `data_nascimento` DATE NOT NULL,
  `cpf` INT NOT NULL,
  `genero` VARCHAR(45) NULL,
  `email` VARCHAR(45) NOT NULL,
  `logradouro` VARCHAR(100) NOT NULL,
  `Endereco_cep` INT NOT NULL,
  `Medico_Funcionarios_idFuncionarios` INT NOT NULL,
  PRIMARY KEY (`idPaciente`),
  CONSTRAINT `fk_Paciente_Medico1`
    FOREIGN KEY (`Medico_Funcionarios_idFuncionarios`)
    REFERENCES `Medico` (`Funcionarios_idFuncionarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Paciente_Endereco1`
    FOREIGN KEY (`Endereco_cep`)
    REFERENCES `Endereco` (`cep`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Paciente_Medico1_idx` ON `Paciente` (`Medico_Funcionarios_idFuncionarios` ASC) VISIBLE;

CREATE INDEX `fk_Paciente_Endereco1_idx` ON `Paciente` (`Endereco_cep` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Receita`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Receita` ;

CREATE TABLE IF NOT EXISTS `Receita` (
  `Paciente_idPaciente` INT NOT NULL,
  `idReceita` INT NOT NULL,
  `data` DATE NOT NULL,
  `assinatura` VARCHAR(45) NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  `Medico_Funcionarios_idFuncionarios` INT NOT NULL,
  PRIMARY KEY (`Paciente_idPaciente`, `idReceita`),
  CONSTRAINT `fk_Receita_Paciente1`
    FOREIGN KEY (`Paciente_idPaciente`)
    REFERENCES `Paciente` (`idPaciente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Receita_Medico1`
    FOREIGN KEY (`Medico_Funcionarios_idFuncionarios`)
    REFERENCES `Medico` (`Funcionarios_idFuncionarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Receita_Paciente1_idx` ON `Receita` (`Paciente_idPaciente` ASC) VISIBLE;

CREATE INDEX `fk_Receita_Medico1_idx` ON `Receita` (`Medico_Funcionarios_idFuncionarios` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Farmaceutico`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Farmaceutico` ;

CREATE TABLE IF NOT EXISTS `Farmaceutico` (
  `Funcionarios_idFuncionarios` INT NOT NULL,
  `crf` INT NOT NULL,
  PRIMARY KEY (`Funcionarios_idFuncionarios`),
  CONSTRAINT `fk_Farmaceutico_Funcionarios1`
    FOREIGN KEY (`Funcionarios_idFuncionarios`)
    REFERENCES `Funcionarios` (`idFuncionarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Saida_Receita`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Saida_Receita` ;

CREATE TABLE IF NOT EXISTS `Saida_Receita` (
  `Medicamentos_idMedicamentos` INT NOT NULL,
  `Paciente_idPaciente` INT NOT NULL,
  `Receita_idReceita` INT NOT NULL,
  `quantidade` INT NOT NULL,
  `dias` INT NOT NULL,
  `horas` DECIMAL NOT NULL,
  `Farmaceutico_Funcionarios_idFuncionarios` INT NOT NULL,
  PRIMARY KEY (`Medicamentos_idMedicamentos`, `Paciente_idPaciente`, `Receita_idReceita`),
  CONSTRAINT `fk_Medicamentos_has_Receita_Medicamentos1`
    FOREIGN KEY (`Medicamentos_idMedicamentos`)
    REFERENCES `Medicamentos` (`idMedicamentos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Medicamentos_has_Receita_Receita1`
    FOREIGN KEY (`Receita_idReceita`)
    REFERENCES `Receita` (`idReceita`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Saida_Receita_Farmaceutico1`
    FOREIGN KEY (`Farmaceutico_Funcionarios_idFuncionarios`)
    REFERENCES `Farmaceutico` (`Funcionarios_idFuncionarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Saida_Receita_Paciente1`
    FOREIGN KEY (`Paciente_idPaciente`)
    REFERENCES `Paciente` (`idPaciente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Medicamentos_has_Receita_Receita1_idx` ON `Saida_Receita` (`Receita_idReceita` ASC) VISIBLE;

CREATE INDEX `fk_Medicamentos_has_Receita_Medicamentos1_idx` ON `Saida_Receita` (`Medicamentos_idMedicamentos` ASC) VISIBLE;

CREATE INDEX `fk_Saida_Receita_Farmaceutico1_idx` ON `Saida_Receita` (`Farmaceutico_Funcionarios_idFuncionarios` ASC) VISIBLE;

CREATE INDEX `fk_Saida_Receita_Paciente1_idx` ON `Saida_Receita` (`Paciente_idPaciente` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Gerente_Enferm`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Gerente_Enferm` ;

CREATE TABLE IF NOT EXISTS `Gerente_Enferm` (
  `Funcionarios_idFuncionarios` INT NOT NULL,
  `coren` INT NOT NULL,
  PRIMARY KEY (`Funcionarios_idFuncionarios`),
  CONSTRAINT `fk_Enfermeiro_Funcionarios1`
    FOREIGN KEY (`Funcionarios_idFuncionarios`)
    REFERENCES `Funcionarios` (`idFuncionarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Requerimento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Requerimento` ;

CREATE TABLE IF NOT EXISTS `Requerimento` (
  `idRequerimento` INT NOT NULL,
  `data` DATE NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  `Gerente_Enferm_Funcionarios_idFuncionarios` INT NOT NULL,
  PRIMARY KEY (`idRequerimento`),
  CONSTRAINT `fk_Requerimento_Gerente_Enferm1`
    FOREIGN KEY (`Gerente_Enferm_Funcionarios_idFuncionarios`)
    REFERENCES `Gerente_Enferm` (`Funcionarios_idFuncionarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Requerimento_Gerente_Enferm1_idx` ON `Requerimento` (`Gerente_Enferm_Funcionarios_idFuncionarios` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Saida_Requerimento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Saida_Requerimento` ;

CREATE TABLE IF NOT EXISTS `Saida_Requerimento` (
  `Medicamentos_idMedicamentos` INT NOT NULL,
  `Requerimento_idRequerimento` INT NOT NULL,
  `quantidade` INT NOT NULL,
  `Farmaceutico_Funcionarios_idFuncionarios` INT NOT NULL,
  PRIMARY KEY (`Medicamentos_idMedicamentos`, `Requerimento_idRequerimento`),
  CONSTRAINT `fk_Medicamentos_has_Requerimento_Medicamentos1`
    FOREIGN KEY (`Medicamentos_idMedicamentos`)
    REFERENCES `Medicamentos` (`idMedicamentos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Medicamentos_has_Requerimento_Requerimento1`
    FOREIGN KEY (`Requerimento_idRequerimento`)
    REFERENCES `Requerimento` (`idRequerimento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Saida_Requerimento_Farmaceutico1`
    FOREIGN KEY (`Farmaceutico_Funcionarios_idFuncionarios`)
    REFERENCES `Farmaceutico` (`Funcionarios_idFuncionarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Medicamentos_has_Requerimento_Requerimento1_idx` ON `Saida_Requerimento` (`Requerimento_idRequerimento` ASC) VISIBLE;

CREATE INDEX `fk_Medicamentos_has_Requerimento_Medicamentos1_idx` ON `Saida_Requerimento` (`Medicamentos_idMedicamentos` ASC) VISIBLE;

CREATE INDEX `fk_Saida_Requerimento_Farmaceutico1_idx` ON `Saida_Requerimento` (`Farmaceutico_Funcionarios_idFuncionarios` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Fornece_Medicamentos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Fornece_Medicamentos` ;

CREATE TABLE IF NOT EXISTS `Fornece_Medicamentos` (
  `Medicamentos_idMedicamentos` INT NOT NULL,
  `Fornecedor_idFornecedor` INT NOT NULL,
  PRIMARY KEY (`Medicamentos_idMedicamentos`, `Fornecedor_idFornecedor`),
  CONSTRAINT `fk_Medicamentos_has_Fornecedor_Medicamentos1`
    FOREIGN KEY (`Medicamentos_idMedicamentos`)
    REFERENCES `Medicamentos` (`idMedicamentos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Medicamentos_has_Fornecedor_Fornecedor1`
    FOREIGN KEY (`Fornecedor_idFornecedor`)
    REFERENCES `Fornecedor` (`idFornecedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Medicamentos_has_Fornecedor_Fornecedor1_idx` ON `Fornece_Medicamentos` (`Fornecedor_idFornecedor` ASC) VISIBLE;

CREATE INDEX `fk_Medicamentos_has_Fornecedor_Medicamentos1_idx` ON `Fornece_Medicamentos` (`Medicamentos_idMedicamentos` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Fone_Fornecedor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Fone_Fornecedor` ;

CREATE TABLE IF NOT EXISTS `Fone_Fornecedor` (
  `Fornecedor_idFornecedor` INT NOT NULL,
  `telefone` INT NOT NULL,
  PRIMARY KEY (`Fornecedor_idFornecedor`, `telefone`),
  CONSTRAINT `fk_Telefone_Forn_Fornecedor1`
    FOREIGN KEY (`Fornecedor_idFornecedor`)
    REFERENCES `Fornecedor` (`idFornecedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Telefone_Forn_Fornecedor1_idx` ON `Fone_Fornecedor` (`Fornecedor_idFornecedor` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Fone_Paciente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Fone_Paciente` ;

CREATE TABLE IF NOT EXISTS `Fone_Paciente` (
  `Paciente_idPaciente` INT NOT NULL,
  `telefone` INT NOT NULL,
  PRIMARY KEY (`Paciente_idPaciente`, `telefone`),
  CONSTRAINT `fk_Telefone_Paci_Paciente1`
    FOREIGN KEY (`Paciente_idPaciente`)
    REFERENCES `Paciente` (`idPaciente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Telefone_Paci_Paciente1_idx` ON `Fone_Paciente` (`Paciente_idPaciente` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Fone_Funcionario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Fone_Funcionario` ;

CREATE TABLE IF NOT EXISTS `Fone_Funcionario` (
  `Funcionarios_idFuncionarios` INT NOT NULL,
  `telefone` INT NOT NULL,
  PRIMARY KEY (`Funcionarios_idFuncionarios`, `telefone`),
  CONSTRAINT `fk_Fone_Funcionario_Funcionarios1`
    FOREIGN KEY (`Funcionarios_idFuncionarios`)
    REFERENCES `Funcionarios` (`idFuncionarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Fone_Funcionario_Funcionarios1_idx` ON `Fone_Funcionario` (`Funcionarios_idFuncionarios` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
